define character.n = Character("Nell", image="nell")
define character.c = Character("Carla")
define character.d = Character("Dominique")
define character.e = Character("Eileen")
define character.r = Character("Rocco")
