define character.n = Character("Nell", image="nell")
define character.c = Character("Carla", image="carla")
define character.d = Character("Dominique", image="dominique")
define character.e = Character("Eileen", image="eileen")
define character.r = Character("Raquel", image="raquel")
