define character.n = Character("Nell", image="nell")
define character.c = Character("Carla", image="nell")
define character.d = Character("Dominique", image="nell")
define character.e = Character("Eileen", image="nell")
define character.r = Character("Raquel", image="nell")
